[[Mineos]]
arch = "x86_64"
git-tree-sha1 = "bac7fc8b4094cbace291c1607199621e9ef65dde"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Mineos.download]]
    sha256 = "3dcf3aa0e92f1986aaa2fe1f9d9a74fea077b1f8fe74a71b1469506483c7b678"
    url = "https://github.com/JuliaBinaryWrappers/Mineos_jll.jl/releases/download/Mineos-v1.0.0+0/Mineos.v1.0.0.x86_64-linux-gnu-libgfortran4.tar.gz"
[[Mineos]]
arch = "aarch64"
git-tree-sha1 = "e965dfba7c20331b6cf7b3d57e22c9105119b283"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Mineos.download]]
    sha256 = "e1d9da80ba68864ce6b78593448b6ba17666f8d7d5d691274935b910333ee7a4"
    url = "https://github.com/JuliaBinaryWrappers/Mineos_jll.jl/releases/download/Mineos-v1.0.0+0/Mineos.v1.0.0.aarch64-linux-musl-libgfortran4.tar.gz"
[[Mineos]]
arch = "i686"
git-tree-sha1 = "445ba818ab31ab5191a4ccf7e6af15d9f3e3e4f0"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Mineos.download]]
    sha256 = "8fe2c92373305c19d930622ca7ab52bf4658c955842863559f0d49fd9a780b3f"
    url = "https://github.com/JuliaBinaryWrappers/Mineos_jll.jl/releases/download/Mineos-v1.0.0+0/Mineos.v1.0.0.i686-linux-gnu-libgfortran3.tar.gz"
[[Mineos]]
arch = "x86_64"
git-tree-sha1 = "14e22c75ec8b9d7f326ee0da448367b7f1a07a87"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Mineos.download]]
    sha256 = "0f899f308c60931c9f26464010b3809fd12e7599ae86f14d367771a9ad3f0832"
    url = "https://github.com/JuliaBinaryWrappers/Mineos_jll.jl/releases/download/Mineos-v1.0.0+0/Mineos.v1.0.0.x86_64-linux-musl-libgfortran3.tar.gz"
[[Mineos]]
arch = "aarch64"
git-tree-sha1 = "4bcb748fef1262ec5f73125f3e5ad7e3891e5ecc"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Mineos.download]]
    sha256 = "239a83fe39c10552aedda2586746a6e440c4cae063ea3783e8c72d6f9c70a893"
    url = "https://github.com/JuliaBinaryWrappers/Mineos_jll.jl/releases/download/Mineos-v1.0.0+0/Mineos.v1.0.0.aarch64-linux-musl-libgfortran3.tar.gz"
[[Mineos]]
arch = "i686"
git-tree-sha1 = "a5f22bcf635d7a509954ea0ec142da90faf2eb4a"
libgfortran_version = "5.0.0"
os = "windows"

    [[Mineos.download]]
    sha256 = "dd6424a5ef885f170eaeef3406125f909144e269a68f4480799ef6683ac774ab"
    url = "https://github.com/JuliaBinaryWrappers/Mineos_jll.jl/releases/download/Mineos-v1.0.0+0/Mineos.v1.0.0.i686-w64-mingw32-libgfortran5.tar.gz"
[[Mineos]]
arch = "aarch64"
git-tree-sha1 = "ca7d8ff44137f2142adc61734e3c6614378b8303"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Mineos.download]]
    sha256 = "c3b1536bd049855f9e8565d36ff624e903788c25b18633d251c017574b66dee9"
    url = "https://github.com/JuliaBinaryWrappers/Mineos_jll.jl/releases/download/Mineos-v1.0.0+0/Mineos.v1.0.0.aarch64-linux-musl-libgfortran5.tar.gz"
[[Mineos]]
arch = "armv7l"
git-tree-sha1 = "580de8329e14fce82801c60a62f5b45cc87f909b"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Mineos.download]]
    sha256 = "22bb10f36dafb71e732fedf718fd0cf55bbb27857eb6a34a2854e4a85588491f"
    url = "https://github.com/JuliaBinaryWrappers/Mineos_jll.jl/releases/download/Mineos-v1.0.0+0/Mineos.v1.0.0.arm-linux-musleabihf-libgfortran5.tar.gz"
[[Mineos]]
arch = "armv7l"
git-tree-sha1 = "687d9d6efd8539a1df1c50fa28f65d5827e5bc88"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Mineos.download]]
    sha256 = "91900331ed1f39fab308a5fd7d2fa6a2070ca8e052b67c49e82c85f8ff3e6408"
    url = "https://github.com/JuliaBinaryWrappers/Mineos_jll.jl/releases/download/Mineos-v1.0.0+0/Mineos.v1.0.0.arm-linux-musleabihf-libgfortran3.tar.gz"
[[Mineos]]
arch = "i686"
git-tree-sha1 = "60752469690f8307a1de81f98c953676a18b17d2"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Mineos.download]]
    sha256 = "c9a6410de0dd44af8bd010049262377658ecd791be00d271d224a9aea7799357"
    url = "https://github.com/JuliaBinaryWrappers/Mineos_jll.jl/releases/download/Mineos-v1.0.0+0/Mineos.v1.0.0.i686-linux-musl-libgfortran5.tar.gz"
[[Mineos]]
arch = "x86_64"
git-tree-sha1 = "20194dd1aecb09b6921aa644b61ee5e7f237be37"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[Mineos.download]]
    sha256 = "ff8d24aea99c40be04570918590b1f3eb1ab38deb8cf7c2c6467cf01b0b0fd90"
    url = "https://github.com/JuliaBinaryWrappers/Mineos_jll.jl/releases/download/Mineos-v1.0.0+0/Mineos.v1.0.0.x86_64-unknown-freebsd11.1-libgfortran4.tar.gz"
[[Mineos]]
arch = "x86_64"
git-tree-sha1 = "f533a7c1ba0268cb424c6ec42f62c8e424559280"
libgfortran_version = "5.0.0"
os = "windows"

    [[Mineos.download]]
    sha256 = "61a75530caa69a965d33fc2e678d563ed240e21ee74139adcc686000918f154b"
    url = "https://github.com/JuliaBinaryWrappers/Mineos_jll.jl/releases/download/Mineos-v1.0.0+0/Mineos.v1.0.0.x86_64-w64-mingw32-libgfortran5.tar.gz"
[[Mineos]]
arch = "armv7l"
git-tree-sha1 = "bf0c938c8fb469e2a759efad895d1cd952d4e4eb"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Mineos.download]]
    sha256 = "2248167cdba7b8b18aecb863e004f16cee95d7d170122428944012cd9f635fd5"
    url = "https://github.com/JuliaBinaryWrappers/Mineos_jll.jl/releases/download/Mineos-v1.0.0+0/Mineos.v1.0.0.arm-linux-gnueabihf-libgfortran5.tar.gz"
[[Mineos]]
arch = "powerpc64le"
git-tree-sha1 = "0848b4caf12420e3bbee4a55fd08bd1fdde497a3"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Mineos.download]]
    sha256 = "b267551857fa972770b4f429b4e249fe8cc331706e492ea42436cd1ce9677419"
    url = "https://github.com/JuliaBinaryWrappers/Mineos_jll.jl/releases/download/Mineos-v1.0.0+0/Mineos.v1.0.0.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[Mineos]]
arch = "i686"
git-tree-sha1 = "f7f2f21dfc060d0b4431d813064cb4c3ce20bbf0"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Mineos.download]]
    sha256 = "dc912603c5814b951ad79005d0df1ef49f460120590675200a1d6338a566e811"
    url = "https://github.com/JuliaBinaryWrappers/Mineos_jll.jl/releases/download/Mineos-v1.0.0+0/Mineos.v1.0.0.i686-linux-gnu-libgfortran5.tar.gz"
[[Mineos]]
arch = "armv7l"
git-tree-sha1 = "69269985d9f67f07651f3bc27d4b94fa8f53ffee"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Mineos.download]]
    sha256 = "feae9489a0c876cba63eed00cc35a7515f3f12f5550d40dc71d2a28fba410271"
    url = "https://github.com/JuliaBinaryWrappers/Mineos_jll.jl/releases/download/Mineos-v1.0.0+0/Mineos.v1.0.0.arm-linux-gnueabihf-libgfortran3.tar.gz"
[[Mineos]]
arch = "x86_64"
git-tree-sha1 = "cdea482b30f54b6cfea42c5857fbd66f6beeebb2"
libgfortran_version = "3.0.0"
os = "macos"

    [[Mineos.download]]
    sha256 = "5c3446245a83cda64d480cf0af37cc37aea1d11590e0359e0c79f735e52d5371"
    url = "https://github.com/JuliaBinaryWrappers/Mineos_jll.jl/releases/download/Mineos-v1.0.0+0/Mineos.v1.0.0.x86_64-apple-darwin14-libgfortran3.tar.gz"
[[Mineos]]
arch = "armv7l"
git-tree-sha1 = "f3b70c265a27c206f8a442737b12c2ca5b10d1d2"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Mineos.download]]
    sha256 = "0432a99eb214f3503a9e26121e44cfaf4e3164e76e32d36707fa2034749fa8d8"
    url = "https://github.com/JuliaBinaryWrappers/Mineos_jll.jl/releases/download/Mineos-v1.0.0+0/Mineos.v1.0.0.arm-linux-gnueabihf-libgfortran4.tar.gz"
[[Mineos]]
arch = "x86_64"
git-tree-sha1 = "e7a07f8d510492fca1ce4d092c874df7e17c6c12"
libgfortran_version = "5.0.0"
os = "macos"

    [[Mineos.download]]
    sha256 = "118c1cc9db6b14baa4cd447a0cc81dbe7be594c5b235e411839bab8cae46a737"
    url = "https://github.com/JuliaBinaryWrappers/Mineos_jll.jl/releases/download/Mineos-v1.0.0+0/Mineos.v1.0.0.x86_64-apple-darwin14-libgfortran5.tar.gz"
[[Mineos]]
arch = "x86_64"
git-tree-sha1 = "70b4cd2761c4d3337e310598d8486787f7aad34a"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[Mineos.download]]
    sha256 = "3e068237921c7ce227a85d5e3716dbe83e10df24d409f84fe03f5e3bd5f7aefa"
    url = "https://github.com/JuliaBinaryWrappers/Mineos_jll.jl/releases/download/Mineos-v1.0.0+0/Mineos.v1.0.0.x86_64-unknown-freebsd11.1-libgfortran5.tar.gz"
[[Mineos]]
arch = "x86_64"
git-tree-sha1 = "57c307f3a22999236c881f52d588d5042a7368be"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Mineos.download]]
    sha256 = "ff2c58c305b941d3ed690edc2154e6255322dabc99af5cbfad24834c408b746a"
    url = "https://github.com/JuliaBinaryWrappers/Mineos_jll.jl/releases/download/Mineos-v1.0.0+0/Mineos.v1.0.0.x86_64-linux-gnu-libgfortran3.tar.gz"
[[Mineos]]
arch = "aarch64"
git-tree-sha1 = "fd2dd9121a6403885780875d915bc56014e278f4"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Mineos.download]]
    sha256 = "384490b3efdc8a236b8928f1c5e2a65b791ddca7651bf1e77db13ccab935260f"
    url = "https://github.com/JuliaBinaryWrappers/Mineos_jll.jl/releases/download/Mineos-v1.0.0+0/Mineos.v1.0.0.aarch64-linux-gnu-libgfortran3.tar.gz"
[[Mineos]]
arch = "x86_64"
git-tree-sha1 = "c20aab7e22c6871175a3d89a3b42df1739c992d7"
libgfortran_version = "4.0.0"
os = "windows"

    [[Mineos.download]]
    sha256 = "1e749b7924a7e90104cc439c90f1076ba4a507ba96040e9356b7bc196881fa1a"
    url = "https://github.com/JuliaBinaryWrappers/Mineos_jll.jl/releases/download/Mineos-v1.0.0+0/Mineos.v1.0.0.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[Mineos]]
arch = "aarch64"
git-tree-sha1 = "4be4853b339686065cd4d45853d1495b9523fcc8"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Mineos.download]]
    sha256 = "1d6c2eec0b2b74c948a9a19b2d5ebcba0355dfe1340fc6ccad7abd40ae134519"
    url = "https://github.com/JuliaBinaryWrappers/Mineos_jll.jl/releases/download/Mineos-v1.0.0+0/Mineos.v1.0.0.aarch64-linux-gnu-libgfortran5.tar.gz"
[[Mineos]]
arch = "x86_64"
git-tree-sha1 = "dbf84d7474a0f0e14ab43d3785f29a18a45744b4"
libgfortran_version = "3.0.0"
os = "windows"

    [[Mineos.download]]
    sha256 = "ee6c8539620a3b41d70cde3c198d86e38c2d204ab451401538dee7b7096705b3"
    url = "https://github.com/JuliaBinaryWrappers/Mineos_jll.jl/releases/download/Mineos-v1.0.0+0/Mineos.v1.0.0.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[Mineos]]
arch = "powerpc64le"
git-tree-sha1 = "4c749b0a85d18f09470e5cea93dcefe09fc597f5"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Mineos.download]]
    sha256 = "04af0905181ee6d6cdf385fef23ee43012b135f12cfb22149997ca747a084d52"
    url = "https://github.com/JuliaBinaryWrappers/Mineos_jll.jl/releases/download/Mineos-v1.0.0+0/Mineos.v1.0.0.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[Mineos]]
arch = "aarch64"
git-tree-sha1 = "83c99b5da1ba6ef9fccbe1d8be01695abc13a0fe"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Mineos.download]]
    sha256 = "b87af2e59671850388afe2e605c0c84caae73d31929cf919cc7f037b622ecdb9"
    url = "https://github.com/JuliaBinaryWrappers/Mineos_jll.jl/releases/download/Mineos-v1.0.0+0/Mineos.v1.0.0.aarch64-linux-gnu-libgfortran4.tar.gz"
[[Mineos]]
arch = "armv7l"
git-tree-sha1 = "bf7bb6b6189edc38ba8d669fa9f13629e34e1b5f"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Mineos.download]]
    sha256 = "8310b2cd62e97d31b49c59269bb01b52dd7ce3c56a01d3d72be4b9b30965ab0e"
    url = "https://github.com/JuliaBinaryWrappers/Mineos_jll.jl/releases/download/Mineos-v1.0.0+0/Mineos.v1.0.0.arm-linux-musleabihf-libgfortran4.tar.gz"
[[Mineos]]
arch = "i686"
git-tree-sha1 = "ae5834dd26aee07b87c93792b4906c0a3633b3b5"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Mineos.download]]
    sha256 = "a1c5ed0a4517b0ac00c8420222e756e0d380d8d8b7a1abc7c53fc5feed93c77a"
    url = "https://github.com/JuliaBinaryWrappers/Mineos_jll.jl/releases/download/Mineos-v1.0.0+0/Mineos.v1.0.0.i686-linux-musl-libgfortran3.tar.gz"
[[Mineos]]
arch = "x86_64"
git-tree-sha1 = "a9acaa71e6f6e93e67f2698d23642b43662ae011"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Mineos.download]]
    sha256 = "90f3aa40ccb586c0bd882165c55070cebc5f8364b2a964b965a4505a33174d38"
    url = "https://github.com/JuliaBinaryWrappers/Mineos_jll.jl/releases/download/Mineos-v1.0.0+0/Mineos.v1.0.0.x86_64-linux-musl-libgfortran4.tar.gz"
[[Mineos]]
arch = "x86_64"
git-tree-sha1 = "4d3aedd02f7353a998d2ea96dd4ae1578fbaf2cb"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Mineos.download]]
    sha256 = "5791db891ee5f6dfb37c248085f1e033721b3f9ffbb249a6bb3bd7ff4652fb50"
    url = "https://github.com/JuliaBinaryWrappers/Mineos_jll.jl/releases/download/Mineos-v1.0.0+0/Mineos.v1.0.0.x86_64-linux-musl-libgfortran5.tar.gz"
[[Mineos]]
arch = "powerpc64le"
git-tree-sha1 = "d1da816d96df52695b2dca6de7f031f260034e23"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Mineos.download]]
    sha256 = "604714b2235ed09c2372d55a405923c680e9fa4c53694123c4f0eb08129cee77"
    url = "https://github.com/JuliaBinaryWrappers/Mineos_jll.jl/releases/download/Mineos-v1.0.0+0/Mineos.v1.0.0.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[Mineos]]
arch = "x86_64"
git-tree-sha1 = "bb3ccad94e2b8baf2dbf62ae653f2da3f3339a10"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Mineos.download]]
    sha256 = "2827dd0975d5f1f91bde2470747b2e8614d93c05292b03e77ed2ea0b97dc7af0"
    url = "https://github.com/JuliaBinaryWrappers/Mineos_jll.jl/releases/download/Mineos-v1.0.0+0/Mineos.v1.0.0.x86_64-linux-gnu-libgfortran5.tar.gz"
[[Mineos]]
arch = "i686"
git-tree-sha1 = "e2110a7831ed337ec74bddd85a15e5dab1c56fa6"
libgfortran_version = "4.0.0"
os = "windows"

    [[Mineos.download]]
    sha256 = "b0ee33b799bda824918ec945c3469235ed5d844716d28db5b6da21d72860d0f3"
    url = "https://github.com/JuliaBinaryWrappers/Mineos_jll.jl/releases/download/Mineos-v1.0.0+0/Mineos.v1.0.0.i686-w64-mingw32-libgfortran4.tar.gz"
[[Mineos]]
arch = "x86_64"
git-tree-sha1 = "065a165a6d7141a85eb7b6b0dec5b35d773d4fbe"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[Mineos.download]]
    sha256 = "89ee42ac2171a3f4350baf63c1669832688f63f9a391afa769cf149dd867cfc7"
    url = "https://github.com/JuliaBinaryWrappers/Mineos_jll.jl/releases/download/Mineos-v1.0.0+0/Mineos.v1.0.0.x86_64-unknown-freebsd11.1-libgfortran3.tar.gz"
[[Mineos]]
arch = "i686"
git-tree-sha1 = "908e51bec5b73f56b50b3e838455a260177aa83c"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Mineos.download]]
    sha256 = "7b40b41c18e03f839d58e4c85d2e586ca44e519614c25f862045a69c935a02f0"
    url = "https://github.com/JuliaBinaryWrappers/Mineos_jll.jl/releases/download/Mineos-v1.0.0+0/Mineos.v1.0.0.i686-linux-gnu-libgfortran4.tar.gz"
[[Mineos]]
arch = "i686"
git-tree-sha1 = "3bb8ec1355538fc64bfbfddfa3633b38520c7096"
libgfortran_version = "3.0.0"
os = "windows"

    [[Mineos.download]]
    sha256 = "9ac367075f602b1571065619568a198fc7f10d3caba6c03d600563b1cf66fa9b"
    url = "https://github.com/JuliaBinaryWrappers/Mineos_jll.jl/releases/download/Mineos-v1.0.0+0/Mineos.v1.0.0.i686-w64-mingw32-libgfortran3.tar.gz"
[[Mineos]]
arch = "x86_64"
git-tree-sha1 = "90467ecc6d265a25b68ee41e2c0a06604d720fd3"
libgfortran_version = "4.0.0"
os = "macos"

    [[Mineos.download]]
    sha256 = "c0fc12b13ae052d361752a1ebe40d14a7a4f9c75edabf0572ca51a81f060c20f"
    url = "https://github.com/JuliaBinaryWrappers/Mineos_jll.jl/releases/download/Mineos-v1.0.0+0/Mineos.v1.0.0.x86_64-apple-darwin14-libgfortran4.tar.gz"
[[Mineos]]
arch = "i686"
git-tree-sha1 = "8bbf62a4987a597c99d1fef1588ad777d8b795ff"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Mineos.download]]
    sha256 = "e6adfb912627ac759395bf6fc9b0924e12a0f8d28def48a0acf8e17b918c1bdc"
    url = "https://github.com/JuliaBinaryWrappers/Mineos_jll.jl/releases/download/Mineos-v1.0.0+0/Mineos.v1.0.0.i686-linux-musl-libgfortran4.tar.gz"
